# Generated by Django 5.1.3 on 2024-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/audio/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('speech_rate', models.FloatField(blank=True, null=True)),
                ('most_used_words', models.JSONField(blank=True, null=True)),
                ('filler_word_count', models.IntegerField(blank=True, null=True)),
                ('vocabulary_richness', models.FloatField(blank=True, null=True)),
                ('avg_pitch', models.FloatField(blank=True, null=True)),
                ('avg_loudness', models.FloatField(blank=True, null=True)),
                ('loudness_variation', models.FloatField(blank=True, null=True)),
                ('emotion_analysis', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
