# Generated by Django 5.1.3 on 2024-11-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalQueryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/legal_queries/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('fact_check_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
