# Generated by Django 5.1.3 on 2024-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0002_legalqueryanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/')),
            ],
        ),
    ]
