# Generated by Django 5.1.3 on 2024-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysis',
            name='file_hash',
            field=models.CharField(default='no_hash', max_length=32, unique=True),
        ),
    ]
