# Generated by Django 5.1.3 on 2024-11-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0004_audioanalysis_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioanalysis',
            name='file_hash',
        ),
    ]
